package com.example.skillabus.ui.theme


import androidx.annotation.DrawableRes
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import com.example.skillabus.R


@Immutable
data class SkillabusIcons(
    @DrawableRes val arrowUp: Int,
    @DrawableRes val arrowDown: Int,
    @DrawableRes val arrowLeft: Int,
    @DrawableRes val arrowRight: Int,
    @DrawableRes val arrowLeftCircle: Int,
    @DrawableRes val arrowRightCircle: Int,
    @DrawableRes val chevronUp: Int,
    @DrawableRes val chevronDown: Int,
    @DrawableRes val chevronLeft: Int,
    @DrawableRes val chevronRight: Int,
    @DrawableRes val download: Int,
    @DrawableRes val downloadCloud: Int,
    @DrawableRes val upload: Int,
    @DrawableRes val uploadCloud: Int,
    @DrawableRes val logIn: Int,
    @DrawableRes val logOut: Int,
    @DrawableRes val externalLink: Int,
    @DrawableRes val activity: Int,
    @DrawableRes val alertCircle: Int,
    @DrawableRes val alertTriangle: Int,
    @DrawableRes val info: Int,
    @DrawableRes val xCircle: Int,
    @DrawableRes val x: Int,
    @DrawableRes val plusCircle: Int,
    @DrawableRes val plus: Int,
    @DrawableRes val edit1: Int,
    @DrawableRes val edit2: Int,
    @DrawableRes val edit3: Int,
    @DrawableRes val search: Int,
    @DrawableRes val gear: Int,
    @DrawableRes val send: Int,
    @DrawableRes val share: Int,
    @DrawableRes val delete: Int,
    @DrawableRes val archive: Int,
    @DrawableRes val home: Int,
    @DrawableRes val menu: Int,
    @DrawableRes val user: Int,
    @DrawableRes val users: Int,
    @DrawableRes val userPlus: Int,
    @DrawableRes val userX: Int,
    @DrawableRes val userMinus: Int,
    @DrawableRes val checkMark: Int,
    @DrawableRes val calendar: Int,
    @DrawableRes val lock: Int,
    @DrawableRes val book: Int,
    @DrawableRes val bookOpen: Int,
    @DrawableRes val bookMark: Int,
    @DrawableRes val award: Int,
    @DrawableRes val star: Int,
    @DrawableRes val table: Int,
    @DrawableRes val clock: Int,
)


val Icons = SkillabusIcons(
    arrowUp = R.drawable.arrow_up,
    arrowDown = R.drawable.arrow_down,
    arrowLeft = R.drawable.arrow_left,
    arrowRight =R.drawable.arrow_right,
    arrowLeftCircle =R.drawable.arrow_left_circle,
    arrowRightCircle =R.drawable.arrow_right_circle,
    chevronUp =R.drawable.chevron_up,
    chevronDown =R.drawable.chevron_down,
    chevronLeft =R.drawable.chevron_left,
    chevronRight =R.drawable.chevron_right,
    download =R.drawable.download,
    downloadCloud =R.drawable.download_cloud,
    upload =R.drawable.upload,
    uploadCloud =R.drawable.upload_cloud,
    logIn =R.drawable.log_in,
    logOut =R.drawable.log_out,
    externalLink =R.drawable.external_link,
    activity =R.drawable.activity,
    alertCircle =R.drawable.alert_circle,
    alertTriangle =R.drawable.alert_triangle,
    info =R.drawable.info,
    xCircle =R.drawable.x_circle,
    x =R.drawable.x,
    plusCircle =R.drawable.plus_circle,
    plus =R.drawable.plus,
    edit1 =R.drawable.edit_1,
    edit2 =R.drawable.edit_2,
    edit3 =R.drawable.edit_3,
    search =R.drawable.search,
    gear =R.drawable.gear,
    send =R.drawable.send,
    share =R.drawable.share_2,
    delete =R.drawable.delete,
    archive =R.drawable.archive,
    home =R.drawable.home,
    menu =R.drawable.menu,
    user =R.drawable.user,
    users =R.drawable.users,
    userPlus =R.drawable.user_plus,
    userX =R.drawable.user_x,
    userMinus =R.drawable.user_minus,
    checkMark =R.drawable.checkmark,
    calendar =R.drawable.calendar,
    lock =R.drawable.lock,
    book =R.drawable.book,
    bookOpen =R.drawable.book_open,
    bookMark =R.drawable.bookmark,
    award =R.drawable.award,
    star =R.drawable.star,
    table =R.drawable.table,
    clock =R.drawable.clock,
)